### PR TITLE
Fix compilation hanging

### PR DESCRIPTION
**Pull request by Akryum**

### CODE REVIEW

**Comment by banderson5144** [comment]
So the thing is, when I debug this in the latest version of Atom (1.12) it seems that all of CoffeeScript is broken. So even the reference to ```@obj``` is broken

**Comment by Akryum** [comment]
Well, we got the addon running with this change this morning with Atom 1.12.6 on Windows 7.

**Comment by Szandor72** [comment]
I can confirm this little code change gets me to see save results again. Thank you!

**Comment by EleazarCrusader** [comment]
How did you get this change into your build?  I need to make this change if it isn't going to get built soon.

**Comment by brandonmikeska** [comment]
Any update on this? Can we update something manually until this is pushed?

**Comment by Akryum** [comment]
You can edit manually the file in the package folder.
On Windows, it should be located here: `C:\Users\<UserName>\.atom\packages\MavensMate-Atom`

**Comment by joeferraro** [comment]
v1.0.10

**Comment by brandonmikeska** [comment]
@joeferraro thanks a bunch!

**Comment by EleazarCrusader** [comment]
Awesome!  Thanks for the quick turnaround.

At your service,

Mark H. Morrison



On Dec 14, 2016, at 9:48 AM, Joe Ferraro <notifications@github.com> wrote:

v1.0.10

**Pull request merged**
